Kubernetes
SaraMmejia/Base-de-Datos--Proyeto-Make-It-Real pull request #16
Opened 2020-06-16 15:13 UTC by SaraMmejia

Buenos días! ... esta es la aplicación ya con Docker y Kubernetes

2020-06-17 15:49 UTC, simonhoyos requested changes

2020-06-17 15:49 UTC, simonhoyos commented on package.json
> +    "bcryptjs": "^2.4.3",
Por qué este cambio?

2020-06-17 18:31 UTC, SaraMmejia commented on package.json
> +    "bcryptjs": "^2.4.3",
Definitivamente solomane me corre con bcryptjs, con el bcrypt solo me aparece el error

2020-06-26 02:04 UTC, SaraMmejia commented on package.json
> +    "bcryptjs": "^2.4.3",
Ya quedo eliminado el bcryptjs

2020-06-30 21:20 UTC, simonhoyos requested changes

2020-06-30 21:20 UTC, simonhoyos commented on package.json
> +    "bcryptjs": "^2.4.3",
y probaste borrando la carpeta node_modules y volviendo a correer `npm install`?

2020-06-30 21:20 UTC, simonhoyos commented on src/controllers/provider.controller.js
> +const bcrypt = require('bcryptjs');
Los requires deben actulizarce para reflejar el cambio a bcrypt

2020-06-30 22:42 UTC, SaraMmejia commented on package.json
> +    "bcryptjs": "^2.4.3",
Ya quedo eliminado el bcryptjs. Quedo atenta ante las correcciones

2020-07-01 11:49 UTC, simonhoyos requested changes

2020-07-01 11:49 UTC, simonhoyos commented on .gitignore
> +.prettierrc
Prettier si se sube a github

2020-07-01 14:46 UTC, SaraMmejia commented on .gitignore
> +.prettierrc
Ok!! Perfecto ya la subo entonces ... Muchas gracias

2020-07-01 14:58 UTC, SaraMmejia commented on .gitignore
> +.prettierrc
Ya quedó listo :D

2020-07-02 15:36 UTC, simonhoyos approved these changes

2020-07-02 16:44 UTC, merged