Nodemailer
SaraMmejia/Base-de-Datos--Proyeto-Make-It-Real pull request #18
Opened 2020-06-30 21:49 UTC by BrianOlaya

![image](https://user-images.githubusercontent.com/48833124/86180265-61dd5000-baf1-11ea-8772-49963b0963dd.png)

Cordial Saludo se realiza configuración de envío de correos para el cliente y proveedor.

2020-07-01 11:45 UTC, simonhoyos requested changes

2020-07-01 11:45 UTC, simonhoyos commented on src/controllers/client.controller.js
> +      verify(transporter);
El verify es para probar que el transporter está funcionando como debería. No es necesario dejarlo en el código que va para producción.

2020-07-01 11:45 UTC, simonhoyos commented on src/controllers/provider.controller.js
> +      verify(transporter);
Lo mismo de arriba

2020-07-01 15:18 UTC, BrianOlaya commented on src/controllers/provider.controller.js
> +      verify(transporter);
Se elimina function verify.

2020-07-01 15:18 UTC, BrianOlaya commented on src/controllers/client.controller.js
> +      verify(transporter);
Se elimina function verify.

2020-07-02 15:35 UTC, simonhoyos approved these changes

2020-07-02 21:24 UTC, merged